#' Classify Reads as Case or Control Based on Methylation Profiles
#'
#' This function classifies reads in the `reads` table of a DuckDB database
#' as either `"case"`, `"control"`, or `"unknown"` based on similarity
#' to reference methylation fractions in a `key_table` (e.g., a collapsed windows file).
#' Classification is based on how close the read's `mh_frac` is to the average
#' case or control `mh_frac`, within a user-defined `meth_diff_threshold`.
#'
#' @param mod_db Path to a DuckDB `.db` file created by this package (e.g., from `summarize_mod_reads()`).
#' @param input_table Character. Name of the reads table in which you want to classify
#'   the reads. Default is \code{"reads"}. Required columns: \code{sample_name},
#'   \code{read_id}, \code{mh_frac}.
#' @param output_table Character. Name of the output table to store classified reads
#'   (default: \code{"classified_reads"}).
#' @param key_table Path to a CSV, TSV, or BED file generated by `collapse_mod_windows()`. Must include the columns:
#' `chrom`, `start`, `end`, `avg_mh_frac_control`, `avg_mh_frac_case`, and `avg_meth_diff`.
#' @param case Character string used to label case reads (e.g., `"case"`).
#' @param control Character string used to label control reads (e.g., `"control"`).
#' @param meth_diff_threshold Numeric value specifying the maximum difference in `mh_frac` allowed
#' to match either case or control averages. Must be less than half the minimum absolute value of
#' `avg_meth_diff` to prevent ambiguous classifications.
#' @param reads_table Deprecated. Use \code{input_table} instead.
#' @param table_name Deprecated. Use \code{output_table} instead.
#'
#' @return Invisibly returns the \code{"mod_db"} object (connection closed on return) with
#' \code{current_table} set to \code{output_table}. The output table in the database includes:
#' \itemize{
#'   \item \code{sample_name} – Sample identifier
#'   \item \code{read_id} – Unique read identifier
#'   \item \code{first_cpg_pos} – First CpG position of the read
#'   \item \code{last_cpg_pos} – Last CpG position of the read
#'   \item \code{mh_frac} – Methylation fraction of the read
#'   \item \code{classification} – \code{"case"}, \code{"control"}, or \code{"unknown"}
#' }
#'   \code{last_result} is set to a tibble with columns \code{classification} and \code{n}
#'   (read count per class).
#'
#' @details
#' This function runs entirely in SQL for scalability. It performs an interval join
#' between the `reads` table and the key table on `chrom` and CpG position range,
#' then classifies each read based on proximity of `mh_frac` to either `avg_mh_frac_control` or `avg_mh_frac_case`.
#'
#' @examples
#' \dontrun{
#' classify_mod_reads(
#'   mod_db = "my_data.mod.db",
#'   key_table = "key_table.csv",
#'   case = "treated",
#'   control = "untreated",
#'   meth_diff_threshold = 0.1
#' )
#' }
#'
#' @importFrom DBI dbConnect dbDisconnect dbExistsTable dbExecute dbWriteTable
#' @importFrom duckdb duckdb
#' @importFrom readr read_csv read_tsv
#' @importFrom tools file_ext
#' @importFrom dplyr tbl
#' @importFrom glue glue
#'
#' @export

classify_mod_reads <- function(mod_db,
                           input_table = "reads",
                           output_table = "classified_reads",
                           key_table,
                           case,
                           control,
                           meth_diff_threshold = 0.1,
                           reads_table = NULL,
                           table_name = NULL) {

  if (!is.null(reads_table)) {
    warning("'reads_table' is deprecated; use 'input_table' instead.", call. = FALSE)
    input_table <- reads_table
  }
  if (!is.null(table_name)) {
    warning("'table_name' is deprecated; use 'output_table' instead.", call. = FALSE)
    output_table <- table_name
  }

  start_time <- Sys.time()
  mod_db <- .modhelper_connectDB(mod_db)

  caps <- .auto_duckdb_resource_caps(0.80)
  DBI::dbExecute(mod_db$con, sprintf("PRAGMA temp_directory='%s';", tempdir()))
  DBI::dbExecute(mod_db$con, sprintf("PRAGMA memory_limit='%s';", caps$memory_limit))
  DBI::dbExecute(mod_db$con, sprintf("PRAGMA threads=%d;", caps$threads))

  # Check if reads table exists
  if (!dbExistsTable(mod_db$con, input_table)) {
    stop(glue("Error: Reads table not found in the database.
                     Please run 'summarize_mod_reads()' on database first to generate it."))
  }

  # Check required columns
  .modhelper_check_cols(mod_db$con, input_table, c("sample_name", "read_id", "mh_frac"))

  # Read in key_table and make sure the key_table looks like collapsed_windows...
  file_ext <- file_ext(key_table)

  if (file_ext == "csv") {
    annotation <- read_csv(key_table,
                           show_col_types = FALSE)
  } else if (file_ext %in% c("bed", "tsv")) {
    annotation <- read_tsv(key_table,
                           show_col_types = FALSE)
  } else {
    stop("Invalid file type. Only CSV, TSV, or BED files are supported.")
  }

  # Make sure key_table is a collapsed window format from collapse_windows().
  required_cols <- c("chrom", "start", "end", "avg_mh_frac_control", "avg_mh_frac_case", "avg_meth_diff")

  if (!all(required_cols %in% colnames(annotation))) {
    stop("\nMissing one or more required columns: start, end, avg_mh_frac_control, avg_meth_diff.\nkey_table must be a collapsed_windows table from the function collapse_windows().")
  }


  # Check to make sure threshold, make sure it is less than 1/2 of min_diff... make sure threshold doesn't overlap
  if (any(meth_diff_threshold >= abs(annotation$avg_meth_diff) / 2, na.rm = TRUE)) {
    stop("`\nmeth_diff_threshold` must be less than half the absolute value of all `avg_meth_diff` values.\nThis is to avoid overlapping in classification.\n")
  }

  # Upload annotation as a temporary table
  dbExecute(mod_db$con, "DROP TABLE IF EXISTS temp_key_table;")
  dbWriteTable(mod_db$con, "temp_key_table", annotation, temporary = TRUE)

  if (dbExistsTable(mod_db$con, output_table))
    dbRemoveTable(mod_db$con, output_table)

  query <- glue("
    CREATE TABLE {output_table} AS
    SELECT
      r.sample_name,
      r.read_id,
      r.first_cpg_pos,
      r.last_cpg_pos,
      r.mh_frac,
    CASE
      WHEN ABS(r.mh_frac - k.avg_mh_frac_control) <= {meth_diff_threshold} THEN '{control}'
      WHEN ABS(r.mh_frac - k.avg_mh_frac_case) <= {meth_diff_threshold} THEN '{case}'
    ELSE 'unknown'
    END AS classification
    FROM
      {input_table} r
    JOIN
      temp_key_table k
    ON
      r.chrom = k.chrom
      AND r.first_cpg_pos <= k.end
      AND r.last_cpg_pos >= k.start")

  dbExecute(mod_db$con, query)

  # Drop temporary tables
  dbExecute(mod_db$con, "DROP TABLE IF EXISTS temp_key_table;")

  cat("\n")
  end_time <- Sys.time()

  total_time_difftime <- end_time - start_time

  # Convert the total_time_difftime object to numeric seconds for a reliable comparison
  total_seconds <- as.numeric(total_time_difftime, units = "secs")

  if (total_seconds > 60) {
    # If greater than 60 seconds, convert to numeric minutes for display
    total_minutes <- as.numeric(total_time_difftime, units = "mins")
    message("Classified reads table successfully created as '", output_table, "' in database!",
            "\nTime elapsed: ", round(total_minutes, 2), " minutes\n")
  } else {
    # Otherwise, display in numeric seconds
    message("Classified reads table successfully created as '", output_table, "' in database!",
            "\nTime elapsed: ", round(total_seconds, 2), " seconds\n")
  }

  mod_db$last_result <- dplyr::tbl(mod_db$con, output_table) |>
    dplyr::count(classification) |>
    dplyr::collect()
  mod_db$current_table = output_table

  # print out table header for user
  print(head(tbl(mod_db$con, output_table)))

  mod_db <- .modhelper_cleanup(mod_db)
  invisible(mod_db)
}
